Repository scale-it/algo-builder, pull requests merged in 2021-03, with the labels that each got.

#260 Sample project: remove yarn.lock
  packages/algob/sample-project/yarn.lock
Labels: dependencies

#262 Add script to generate api docs
  examples/asa/package.json
  examples/crowdfunding/package.json
  examples/htlc-pyteal-ts/package.json
  examples/multisig/package.json
  examples/nft/package.json
  examples/permissioned-voting/package.json
  examples/ref-templates/package.json
  examples/restricted-assets/package.json
  examples/signed-txn/package.json
  package.json
  packages/algob/package.json
  packages/runtime/package.json
  packages/types-algosdk/package.json
  yarn.lock
Labels: documentation

#258 Add new command: algob unbox-template
  packages/algob/package.json
  packages/algob/src/builtin-tasks/task-names.ts
  packages/algob/src/builtin-tasks/unbox-template.ts
  packages/algob/src/internal/cli/project-creation.ts
  packages/algob/src/internal/cli/unbox-template.ts
  packages/algob/src/internal/core/tasks/builtin-tasks.ts
  packages/algob/src/internal/util/unpack.ts
  packages/types-download-git-repo/index.d.ts
  packages/types-download-git-repo/package.json
  packages/types-download-git-repo/tsconfig.json
  yarn.lock
Labels: algob, cli

#267 Update README.md and add docs
  README.md
  user-docs/README.md
  user-docs/templates.md
Labels: documentation
