Repository scale-it/algo-builder, pull requests merged in 2021-08, with the labels that each got.

#434 Deploy ASA without using asa.yaml
  CHANGELOG.md
  docs/guide/deployer.md
  docs/guide/execute-transaction.md
  packages/algob/src/internal/deployer.ts
  packages/algob/src/lib/tx.ts
  packages/algob/src/types.ts
  packages/algob/test/internal/deployer.ts
  packages/algob/test/lib/tx.ts
  packages/algob/test/mocks/deployer.ts
  packages/runtime/src/ctx.ts
  packages/runtime/src/index.ts
  packages/runtime/src/lib/asa.ts
  packages/runtime/src/runtime.ts
  packages/runtime/src/types.ts
  packages/runtime/test/src/runtime.ts
  packages/web/src/types.ts
Labels: algob, enhancement, runtime

#436 Test watcher
  CHANGELOG.md
  README.md
  package.json
  packages/algob/package.json
  packages/runtime/package.json
  packages/web/package.json
Labels: enhancement, tests

#437 Fix: yarn add @algo-builder/algob gives dependency issues
  packages/algob/package.json
  packages/runtime/package.json
  yarn.lock
Labels: bug, dependencies

#438 remove "bin" entry from `packages/runtime/package.json`
  CHANGELOG.md
  packages/runtime/package.json
Labels: dependencies

#442 Add dependency zod in `web/package.json`
  CHANGELOG.md
  packages/web/package.json
Labels: dependencies

#443 TEALv4: Sharing data between contracts in runtime
  CHANGELOG.md
  packages/runtime/src/ctx.ts
  packages/runtime/src/errors/errors-list.ts
  packages/runtime/src/interpreter/opcode-list.ts
  packages/runtime/src/lib/constants.ts
  packages/runtime/src/parser/parser.ts
  packages/runtime/src/runtime.ts
  packages/runtime/src/types.ts
  packages/runtime/test/src/interpreter/opcode-list.ts
  packages/runtime/test/src/parser/parser.ts
Labels: runtime, TEALv4

#445 TEALv4: Dynamic Opcode Cost Evaluation
  CHANGELOG.md
  packages/runtime/src/interpreter/interpreter.ts
  packages/runtime/src/parser/parser.ts
  packages/runtime/test/fixtures/dynamic-op-cost/assets/approval-fail.teal
  packages/runtime/test/fixtures/dynamic-op-cost/assets/approval-pass.teal
  packages/runtime/test/fixtures/dynamic-op-cost/assets/clear.teal
  packages/runtime/test/integration/consensus.ts
Labels: runtime, TEALv4
